############################################ User ######################################################
#Create user
POST http://localhost:8080/user
Content-Type: application/json

{
  "username": "username",
  "firstName": "Boris",
  "lastName": "Boris",
  "email": "example@tms.by",
  "password": "examplePassword",
  "phone": "836477652643",
  "userStatus": 0
}

###

#Create user with array
POST http://localhost:8080/user/createWithArray
Content-Type: application/json

[
  {
    "username": "username2",
    "firstName": "Boris",
    "lastName": "Boris",
    "email": "example@tms.by",
    "password": "examplePassword",
    "phone": "836477652643",
    "userStatus": 0
  },
  {
    "username": "username3",
    "firstName": "Boris",
    "lastName": "Boris",
    "email": "example@tms.by",
    "password": "examplePassword",
    "phone": "836477652643",
    "userStatus": 0
  }
]

###
#Delete user
DELETE http://localhost:8080/user/username3


###
#Update user
PUT http://localhost:8080/user/username
Content-Type: application/json

{
  "username": "username",
  "firstName": "Boris Update",
  "lastName": "Boris Update",
  "email": "example@tms.by",
  "password": "examplePassword",
  "phone": "836477652643",
  "userStatus": 0
}

###
#Get user
GET http://localhost:8080/user/username

###
#Login user
GET http://localhost:8080/user/login?username=username&password=examplePassword

###
#Logout user
GET http://localhost:8080/user/logout
X-api-key: edb01569-6e3f-4170-ae6f-8f1e1919284e

############################################ Store ######################################################
#Create order
POST http://localhost:8080/store/order
Content-Type: application/json
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3

{
  "petId": 0,
  "quantity": 0,
  "shipDate": "2021-06-09T11:56:38.357Z",
  "status": "PLACED",
  "complete": true
}

###
#Get order
GET http://localhost:8080/store/order/1
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3

###
#Get inventory
GET http://localhost:8080/store/inventory
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3

###
#Delete order
DELETE http://localhost:8080/store/order/1
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3


############################################ Pet ######################################################
#Create pet
POST http://localhost:8080/pet
Content-Type: application/json
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3r

{
  "id": 0,
  "category": {
    "id": 0,
    "name": "Cats"
  },
  "name": "New cat",
  "tags": [
    {
      "name": "Tag 1"
    },
    {
      "id": 0,
      "name": "Tag 2"
    }
  ],
  "status": "AVAILABLE"
}

###
#Get pet
GET http://localhost:8080/pet/1
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3

###
#Get pet by status
GET http://localhost:8080/pet/findByStatus?status=AVAILABLE
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3

###
#Delete pet
DELETE http://localhost:8080/pet/1
X-api-key: 538f435b-8a98-4a0f-a115-abeaee930bb3
